fetch-in-react-practice | Lucca Rizzi
luccarizzi/c1120-code-solutions pull request #134
Opened 2021-01-24 02:37 UTC by luccarizzi

![new1](https://user-images.githubusercontent.com/69702836/105619688-beb89480-5dba-11eb-88ed-4447c48afd86.gif)

2021-01-25 18:24 UTC, Zhiwutian approved these changes
👍

2021-01-25 18:24 UTC, Zhiwutian commented on fetch-in-react-practice/client/components/app.jsx
> +    const newTodos = this.state.todos;
You do not want to do this, because you are just making a reference to the original array and that will mutate state. Check out this article on alternatives: https://www.samanthaming.com/tidbits/35-es6-way-to-clone-an-array/

2021-01-25 18:24 UTC, Zhiwutian commented on fetch-in-react-practice/client/components/app.jsx
> +    const newTodos = this.state.todos;
same as above

2021-01-25 18:25 UTC, Zhiwutian requested changes
A couple small changes prior to approval! sorry for the first approval being too early!

2021-01-26 03:19 UTC, luccarizzi commented on fetch-in-react-practice/client/components/app.jsx
> +    const newTodos = this.state.todos;
Done.

2021-01-26 03:20 UTC, luccarizzi commented on fetch-in-react-practice/client/components/app.jsx
> +    const newTodos = this.state.todos;
Done.

2021-01-26 18:10 UTC, Zhiwutian approved these changes
👍

2021-01-26 18:11 UTC, merged